# Created by Onorio Catenacci
# 20 April 2022
# This is a workflow to create and publish Chocolately NuGet Packages for Elixir, Erlang and Rebar3


name: Create CNG Packages

on: 
  release:
    types: [published]

jobs:
  create-elixir-release:
    runs-on: windows-latest
    steps:
      # We need curl to fetch the precompiled.zip file.
      - run: choco install curl
      - run: curl -O https://github.com/elixir-lang/elixir/releases/download/v1.13.4/Precompiled.zip


  create-erlang-package:
    runs-on: windows-latest
    steps:
      -run: choco install curl
  
  create-rebar3-package:
    runs-on: windows-latest
    steps: 
      -run: choco install curl


