# Created by Onorio Catenacci
# 20 April 2022
# This is a workflow to create and publish Chocolately NuGet Packages for Elixir, Erlang and Rebar3


name: Create CNG Packages

on: 
  release:
    types: [published]
  
  workflow_dispatch: 

jobs:
  install_curl:
    runs-on: windows-latest
    steps:
      run: |
        choco install curl
        echo "elixir_version=1.13.4" >> $GITHUB_ENV
        echo "erlang_version=24.3.3" >> $GITHUB_ENV
        echo "erts_version=12.3.1" >> $GITHUB_ENV
        echo "rebar3_version=3.18.0" >> $GITHUB_ENV


  create_elixir_package:
    needs: install_curl
    runs-on: windows-latest
    steps:
      - run: curl -O https://github.com/elixir-lang/elixir/releases/download/v${{ env.elixir_version }}/Precompiled.zip


  # create_erlang_package:
  #   needs: install_curl
  #   runs-on: windows-latest
  #   steps:
  
  # create_rebar3_package:
  #   needs: install_curl
  #   runs-on: windows-latest
  #   steps: 


